CREATE TABLE breathing_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inhale_seconds INTEGER NOT NULL CHECK (inhale_seconds BETWEEN 1 AND 30),
    hold_seconds INTEGER NOT NULL CHECK (hold_seconds BETWEEN 0 AND 30),
    exhale_seconds INTEGER NOT NULL CHECK (exhale_seconds BETWEEN 1 AND 30),
    cycle_count INTEGER NOT NULL CHECK (cycle_count BETWEEN 1 AND 20),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
