-- V1 created this CHECK without a name. Resolve its H2-generated name before replacing it.
EXECUTE IMMEDIATE 'ALTER TABLE BREATHING_RECORDS DROP CONSTRAINT ' ||
  QUOTE_IDENT((SELECT tc.CONSTRAINT_NAME
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc
    JOIN INFORMATION_SCHEMA.CHECK_CONSTRAINTS cc
      ON tc.CONSTRAINT_CATALOG = cc.CONSTRAINT_CATALOG
     AND tc.CONSTRAINT_SCHEMA = cc.CONSTRAINT_SCHEMA
     AND tc.CONSTRAINT_NAME = cc.CONSTRAINT_NAME
    WHERE tc.TABLE_SCHEMA = 'PUBLIC'
      AND tc.TABLE_NAME = 'BREATHING_RECORDS'
      AND tc.CONSTRAINT_TYPE = 'CHECK'
      AND cc.CHECK_CLAUSE LIKE '%CYCLE_COUNT%'));

ALTER TABLE breathing_records
  ADD CONSTRAINT chk_breathing_records_cycle_count
  CHECK (cycle_count BETWEEN 1 AND 60);
